### PR TITLE
Hot Fix: Pinning Python Packages

### PR DESCRIPTION
**Pull request by xlabd**
This PR solves issue #7 and #11 

Pip is installing the latest version of `llvmlite` and `numba` which is creating conflicts. I've pinned both the packages to the ONLY version `docker-compose build` executed to its completion.

### CODE REVIEW

**Comment by meokz** [comment]
Thank you for fixing the bug! I'll check in my environment.

**Comment by meokz** [comment]
Looks good to me! Awesome! ✅

**Comment by xlabd** [comment]
@meokz You're welcome. :)
My fix will break after a few months. Pip is going to stop support for python3.5 soon.

**Comment by meokz** [comment]
@xlabd 
Actually, I like static type systems, so I want to upgrade to python3.6 or higher.
However, due to the strong restrictions of libraries such as Cuda, it does not work when changing the python version😂

**Pull request merged**
